// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package database

import (
	"database/sql"
	"time"
)

type Segment struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

type UsersInSegment struct {
	UserID    int64
	SegmentID int64
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpireAt  sql.NullTime
}

type UsersInSegmentsHistory struct {
	UserID      int64
	SegmentID   int64
	SegmentName string
	ActionType  string
	ActionDate  time.Time
}
