// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: segments.sql

package database

import (
	"context"
)

const createSegment = `-- name: CreateSegment :one
INSERT INTO segments (name, created_at, updated_at) 
VALUES ($1, now(), now())
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateSegment(ctx context.Context, name string) (Segment, error) {
	row := q.db.QueryRowContext(ctx, createSegment, name)
	var i Segment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSegment = `-- name: DeleteSegment :exec
DELETE FROM segments 
WHERE name = $1
`

func (q *Queries) DeleteSegment(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteSegment, name)
	return err
}
