# version: "3.7"
# services:
#   database:
#     image: postgres
#     restart: always
#     env_file:
#       - .env
#     ports:
#       - "5432:5432"
#     volumes:
#       - data:/var/lib/postgresql/data
#   server:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     env_file: .env
#     depends_on:
#       - database
#     networks:
#       - default
#     ports:
#     - "8080:8080"
#     restart: on-failure
# volumes:
#   data:
version: '3.8'

services:
  server:
    container_name: server
    build: .
    command: ./wait-for.sh db ./server
    environment:
      - DB_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_DB:-database}:5432/${POSTGRES_DB:-database}?sslmode=disable
      - PORT=${HTTP_PORT:-8080}
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - database
    restart: unless-stopped

  database:
    container_name: database
    hostname: database
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-database}
    # restart: unless-stopped

volumes:
  pg_data: