env: "local" # local, dev, prod

http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 60s

database:
  host: "postgres"
  port: "5432"
  user: "postgres"
  password: "pass"
  name: "postgres"
  sslmode: "disable"
